CREATE DATABASE contasdb;

CREATE TABLE [User](
IdUser INT IDENTITY(1,1)PRIMARY KEY,
FullName VARCHAR(100) NOT NULL,
UserName NVARCHAR(100) NOT NULL,
PasswordHash VARBINARY(MAX),
PasswordSalt VARBINARY(MAX),
)

CREATE TABLE Client(
IdClient INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdUser INT NOT NULL,
[Name] VARCHAR(50) NOT NULL UNIQUE,
[Phone] VARCHAR(50),
Total DECIMAL(8,2)
CONSTRAINT fk_IdUser FOREIGN KEY (IdUser) REFERENCES [User] (IdUser)
);

CREATE TABLE [Order](
IdOrder INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
IdClient INT NOT NULL,
ProductName VARCHAR(100) NOT NULL,
Price DECIMAL(8,2) NOT NULL,
Quantity INT NOT NULL,
[Date] DATE,
Total DECIMAL(8,2) NOT NULL
CONSTRAINT fk_IdCLient FOREIGN KEY (IdClient) REFERENCES Client (IdClient)
);